version: "3"
services:
  recipe-adviser:
    container_name: backend
    build: .
    command: python3 backend/app.py
    volumes:
      - ./backend:/backend
    ports:
      - 5002:5000
    env_file:
      - .env
    tty: true
